### ISSUE TITLE
Server eats itself after 17,000 or so uploads...

### ISSUE THREAD

**Issue by TylerHartman** [pbsds/hatena-server#11]
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-18.9.0-py2.7-linux-i686.egg/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-18.9.0-py2.7-linux-i686.egg/twisted/_threads/_team.py", line 190, in doWork
    task()
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/Twisted-18.9.0-py2.7-linux-i686.egg/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-18.9.0-py2.7-linux-i686.egg/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-18.9.0-py2.7-linux-i686.egg/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-18.9.0-py2.7-linux-i686.egg/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/home/tyler/Desktop/Freenote Beta Server 1.5/hatenadir/ds/v2-xx/frontpage/hotmovies.ugo.py", line 43, in UpdateThreaded
    flipnotes = map(lambda x: x[1], sorted(enumerate(flipnotes), key=sort)[::-1])[:500]
  File "/home/tyler/Desktop/Freenote Beta Server 1.5/hatenadir/ds/v2-xx/frontpage/hotmovies.ugo.py", line 41, in sort
    views, stars = Database.GetFlipnote(ID, flip)[1:3]
exceptions.TypeError: 'bool' object has no attribute '__getitem__'

Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-18.9.0-py2.7-linux-i686.egg/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-18.9.0-py2.7-linux-i686.egg/twisted/_threads/_team.py", line 190, in doWork
    task()
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/Twisted-18.9.0-py2.7-linux-i686.egg/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-18.9.0-py2.7-linux-i686.egg/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-18.9.0-py2.7-linux-i686.egg/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-18.9.0-py2.7-linux-i686.egg/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/home/tyler/Desktop/Freenote Beta Server 1.5/hatenadir/ds/v2-xx/frontpage/likedmovies.ugo.py", line 43, in UpdateThreaded
    flipnotes = map(lambda x: x[1], sorted(enumerate(flipnotes), key=sort)[::-1])[:500]
  File "/home/tyler/Desktop/Freenote Beta Server 1.5/hatenadir/ds/v2-xx/frontpage/likedmovies.ugo.py", line 41, in sort
    views, stars = Database.GetFlipnote(ID, flip)[1:3]
exceptions.TypeError: 'bool' object has no attribute '__getitem__'

Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-18.9.0-py2.7-linux-i686.egg/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-18.9.0-py2.7-linux-i686.egg/twisted/_threads/_team.py", line 190, in doWork
    task()
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/Twisted-18.9.0-py2.7-linux-i686.egg/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-18.9.0-py2.7-linux-i686.egg/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-18.9.0-py2.7-linux-i686.egg/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-18.9.0-py2.7-linux-i686.egg/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/home/tyler/Desktop/Freenote Beta Server 1.5/hatenadir/ds/v2-xx/frontpage/newmovies.ugo.py", line 46, in UpdateThreaded
    pages.append(self.MakePage(flipnotes[i*50:i*50+50], i+1, i<pagecount-1, flipcount))
  File "/home/tyler/Desktop/Freenote Beta Server 1.5/hatenadir/ds/v2-xx/frontpage/newmovies.ugo.py", line 76, in MakePage
    stars = str(Database.GetFlipnote(creatorid, filename)[2])
exceptions.TypeError: 'bool' object has no attribute '__getitem__'

Any chance of this getting fixed?

**Comment by pbsds** [comment]
seems like one of the entries in new_flipnotes.dat don't match whats stored, might be a data corruption
