### ISSUE TITLE
Leafnote database just spams errors in logs

### ISSUE THREAD

**Issue by ghost** [pbsds/hatena-server#36]
i know this isnt the leafnote repo but why
does it when i run a clean database spam the logs full of errors
to be exact this is the error im getting 

Unhandled Error
Traceback (most recent call last):
File "server.py", line 146, in
reactor.run()
File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1283, in run
self.mainLoop()
File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1292, in mainLoop
self.runUntilCurrent()
--- ---
File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 913, in runUntilCurrent
call.func(*call.args, **call.kw)
File "C:\Users\purpe\Desktop\leafnote-master\hatenadir\ds\v2-xx\ch\pokemon.ugo.py", line 35, in Update
if self.newestflip <> Database.Newest[0]:
exceptions.IndexError: list index out of range

**Comment by pbsds** [comment]
Seems like the Database.Newest list is empty, and you're trying to access the first element which does not exist.

**Comment by ghost** [comment]
Yeah uhh this is related to how the database is empty so how to add content to the database then
